### ISSUE TITLE
Missing Tasks for old structures in a new plan on Thailand Local

### ISSUE THREAD

**Issue by madrinekariuki** [opensrp/opensrp-server-web#1051] opened 2022-01-12 09:16 UTC
apk Th-en local v5.3.29
user : `bvbd_test`

It has been noted that structures  from old plans are not having tasks generated in new plans. 
this has been tested on case triggered plans.

tested on 
ef795ee2-44d4-5716-a4e6-0a6a2e2b152a  routine Plan
8040ffb2-6996-4fc6-aeef-48471a4709e6 Case triggered Plan

steps:

- create a new plan `1`, activate and confirm team assignment.
- login to the apk and sync data
- add structures to that plan and sync data
- create another plan `2` in the same OA, 
- activate and confirm team assignment.
- login to the app and sync data, open the structures you created in plan 1 above and see how the tasks section is zero.

screenshot.
![image](https://user-images.githubusercontent.com/84722169/149098775-f77039ff-2b9f-446e-8774-853841f2fb62.png)

structure on the map
![image](https://user-images.githubusercontent.com/84722169/149324049-a5927f53-d7b4-4d6d-92d9-55cf1c5aede6.png)

**Comment by madrinekariuki** [comment] 2022-01-13 10:08
@Rkareko 
As requested please find below Failing test cases for this issue:
- Verify that previously existing structures generate Blood screening tasks in a new plan
- Verify that previously existing structures generate Bednet distribution  tasks in a new plan
- Verify that all Family members have Blood screening tasks in a new plan.
- Verify that for existing mosquito collection structures tasks are generate in a new plan.
-  Verify that for existing Larval dipping structures tasks are generate in a new plan.

**Comment by Rkareko** [comment] 2022-01-13 12:56
For the plan with identifier `ef795ee2-44d4-5716-a4e6-0a6a2e2b152a` has the following distribution of tasks

```
select count(*), code from core.task_metadata where plan_identifier = 'ef795ee2-44d4-5716-a4e6-0a6a2e2b152a' group by 2;
 count |         code         
-------+----------------------
     1 | RACD Register Family
     1 | Bednet Distribution
     2 | Blood Screening

```

**Comment by Rkareko** [comment] 2022-01-14 04:09
@madrinekariuki @samkanga Task generation is failing for plans that are assigned to the jurisdiction with id `ab7e1954-0ac8-475e-b70a-e896babdb649`. This is caused by a null pointer exception that is thrown in the [plan evaluation library](https://github.com/opensrp/opensrp-plan-evaluator/blob/master/src/main/java/org/smartregister/converters/LocationConverter.java#L30) due to [one of the structures](https://servermhealth.ddc.moph.go.th/opensrp/rest/location/9b0bf2d4-e997-4fb7-81ea-6048e28cf541?is_jurisdiction=false)  not having a `status` value in the properties section

It appears only one structure in the entire Thailand Local db is missing a status value i.e

```
 select count(*) from core.structure_metadata where status is null;
 count 
-------
     1
```

A potential fix is to add a null check for the status field. That leaves us with the question of whether or not tasks should be generated for a structure that does not have a status. Sample statuses are `active`, `pending review`, `inactive`

**Comment by madrinekariuki** [comment] 2022-01-14 06:38
@Rkareko 
This has been retested in another location using PlanID `582a50f7-b4b4-5e56-b466-e8bbb0d12278`  (Routine plan)

I note that tasks for existing structures tasks are being generated. 
the tasks that are being generated are:

- BCC
- Bednet distribution
- Blood Screening
- Mosquito Collection
- Larval dipping
- register Family

**Comment by samkanga** [comment] 2022-01-14 06:51
@Rkareko regarding the comment/question:

> A potential fix is to add a null check for the status field. That leaves us with the question of whether or not tasks should be generated for a structure that does not have a status. Sample statuses are active, pending review, inactive

Would the failure of a status be an App issue or what would potentially cause this?

**Comment by Rkareko** [comment] 2022-01-14 06:59
> @Rkareko regarding the comment/question:
> 
> > A potential fix is to add a null check for the status field. That leaves us with the question of whether or not tasks should be generated for a structure that does not have a status. Sample statuses are active, pending review, inactive
> 
> Would the failure of a status be an App issue or what would potentially cause this?

@samkanga Potentially this would be an app issue. The structure was created on `2020-10-16` hence this would have been an issue with an older apk and would be resolved by now since there is on one such structure in the db

**Comment by samkanga** [comment] 2022-01-14 07:09
@Rkareko this is noted. What would be the easiest fix to this? Could we just update the structure to inactive and close out the issue since the test above by @madrinekariuki on another structures appear to work OK. Essentially, there should never be a scenario where a structure has no status.

**Comment by Rkareko** [comment] 2022-01-14 07:15
@samkanga That would suffice for this situation but it would be good in the long run to add a null check for the status field since this causes task gen to fail completely.

**Comment by samkanga** [comment] 2022-01-14 07:18
@Rkareko I do agree. What would be the LoE for that?

**Comment by Rkareko** [comment] 2022-01-14 07:23
@samkanga 2 - 3 hours

**Comment by Rkareko** [comment] 2022-01-18 09:57
@samkanga @madrinekariuki The affected structure has been updated with a `status` value.

**Comment by madrinekariuki** [comment] 2022-01-18 12:00
@Rkareko @samkanga 
this is still happening. this has been retested with below 2 plans and no tasks have been generated. 
`d249ad57-3301-4f89-9b52-8dc0b319ca73 ` case triggered plan
`cf6075bf-7702-575d-b2e9-89b3552585fb`    routine plan

**Comment by madrinekariuki** [comment] 2022-01-28 10:57
@Rkareko  @samkanga 
This is now okay. 
This has been tested on `755aa7e3-a12c-5834-b27d-8fa5995dc110`
all tasks from existing structures are now showing.

screenshots
![image](https://user-images.githubusercontent.com/84722169/151535228-fbdcf334-8f2b-4871-821a-78bf941abb54.png)

**Closed** 2022-01-28 10:57 UTC
Labels: bug, qa+
