### ISSUE TITLE
Fix the location import scripts

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-server-web#721] opened 2021-02-11 08:05 UTC
### Modify the location import script as follows:

- [x] 1) Duplicate locations should be ignored only if they are on the same geo-level & have the same parent location. E.g. There is a `Commune` named "MAHANORO" in the `Region` "ANALANJIROFO", but there is also a `Commune` named "Mahanoro"  in the `Region` "Atsinanana". These should be imported as separate, unique locations.

- [x] 2) We need to ignore the casing of the locations upon import. I.e. `Sofia` and `SOFIA` are the same location. They sit at the same geo level (Region) and they have the same parent location (Madagascar), but upon import, they were created as two separate locations. See this issue: https://github.com/OpenSRP/web/issues/416#issue-800409017 for a screenshot.

### In addition, we need to investigate, if we haven't already, and figure out why the following issues are happening, so we can either modify the import script, or make changes to the locations in the spreadsheet prior to import: 

- [x] Here's an example of a duplicate location, whereby there is no case mismatch on the location spreadsheet, so it might be a different issue to the one above:

![Screen_Shot_2021-02-03_at_2_41_19_PM](https://user-images.githubusercontent.com/3488986/106763803-32ea0800-6605-11eb-98bb-431473aaee27.jpg)

- [x] Child location alignment issues

![Screen_Shot_2021-02-03_at_2_41_19_PM](https://user-images.githubusercontent.com/3488986/106763304-ad665800-6604-11eb-8f37-6776861ab9fe.jpg)

- [x] Child locations missing for certain locations in the side hierarchy dropdown

![Screen_Shot_2021-02-03_at_2_41_19_PM](https://user-images.githubusercontent.com/3488986/106763528-ed2d3f80-6604-11eb-8830-99e2f19e4252.jpg)

**Comment by cafootitt** [comment] 2021-02-11 12:08
This needs to be further clarified, and there are multiple issues occurring here.

1) We need to ignore the casing of the locations upon import. I.e. `Sofia` and `SOFIA` are the same location. They sit at the same geo level (Region) and they have the same parent location (Madagascar), but upon import, they were created as two separate locations. See this issue: https://github.com/OpenSRP/web/issues/416#issue-800409017 for a screenshot.

2) Locations should be sorted A to Z at each level. So sort the first geo level in alphabetical order (A to Z), then sort the 2nd geo-level by A to Z, and so on. This is similar to this command in Excel: 

<img width="512" alt="Screen Shot 2021-02-11 at 12 03 03 PM" src="https://user-images.githubusercontent.com/3488986/107634243-3bf75c80-6c37-11eb-9814-a2ea2b2d839d.png">
<img width="512" alt="Screen Shot 2021-02-11 at 12 03 10 PM" src="https://user-images.githubusercontent.com/3488986/107634236-37cb3f00-6c37-11eb-8963-0ba068dce231.png">

### In addition, I have not heard yet the root cause of these issues that have been observed, so we need to investigate, if we haven't already, and figure out why this is happening, so we can either modify the import script, or make changes to the locations in the spreadsheet prior to import: 

- [ ] Here's an example of a duplicate location, whereby there is no case mismatch on the location spreadsheet, so it might be a different issue to the one above:

![Screen_Shot_2021-02-03_at_2_41_19_PM](https://user-images.githubusercontent.com/3488986/106763803-32ea0800-6605-11eb-98bb-431473aaee27.jpg)

- [ ] Child location alignment issues

![Screen_Shot_2021-02-03_at_2_41_19_PM](https://user-images.githubusercontent.com/3488986/106763304-ad665800-6604-11eb-8f37-6776861ab9fe.jpg)

- [ ] Child locations missing for certain locations in the side hierarchy dropdown

![Screen_Shot_2021-02-03_at_2_41_19_PM](https://user-images.githubusercontent.com/3488986/106763528-ed2d3f80-6604-11eb-8830-99e2f19e4252.jpg)

- [ ] https://github.com/OpenSRP/web/issues/434

**Comment by rehammuzzamil** [comment] 2021-02-11 13:02
@githengi Can you please look at this and brief me on what to pick next? Thanks.

**Comment by githengi** [comment] 2021-02-11 18:37
@rehammuzzamil I will on this on Monday, you dont have to work on anything on this issue

**Comment by githengi** [comment] 2021-02-11 18:44
@rehammuzzamil work on https://github.com/OpenSRP/opensrp-server-web/issues/720

**Comment by githengi** [comment] 2021-02-16 08:36
@cafootitt looks like we have a problem with the below. Please update the missing details here https://docs.google.com/spreadsheets/d/1tm80ZZTt_eajba9QV8-3NMB3fAiOl9CDUDAQdSCBItQ/edit#gid=1943829951



|country|region|district|commune|service_point_name|service_point_type|admin_level_tag|latitude|longitude|
|-------|------|--------|-------|------------------|------------------|---------------|--------|---------|
|Madagascar|Atsimo Atsinanana|Midongy Du Sud||Dreah Midongy|Warehouse|District|||
|Madagascar|Haute Matsiatra|Fianarantsoa I||Dreah Fianarantsoa|Warehouse|District|-20.4548|47.0818|
|Madagascar|Vakinankaratra|Antsirabe I||Drsp Vakinankaratra|DRSP|Region|||
|Madagascar|Vakinankaratra|||Dreah Antsirabe|Warehouse|District|||

**Comment by cafootitt** [comment] 2021-02-16 11:26
@githengi Thanks for this. The missing locations are added to your comment above as well as in the locations spreadsheet - tab: "sorted locations alphabetically"

**Comment by githengi** [comment] 2021-02-16 12:20
Noted, will update the import script

**Comment by cafootitt** [comment] 2021-02-24 11:57
All issues, addressed, closing.

**Closed by cafootitt** 2021-02-24 11:57 UTC
Labels: bug, eusm
