### ISSUE TITLE
Regions are not in alphabetical order on EUSM

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-server-web#726] opened 2021-02-18 10:50 UTC
- Go to locations
- Expand the top location (Madagascar)
- The regions are not listed in alphabetical order:

<img width="1067" alt="Screen Shot 2021-02-18 at 10 38 21 AM" src="https://user-images.githubusercontent.com/3488986/108346229-27721180-71ad-11eb-9ce9-dd4f6649e895.png">

- Same goes for the districts and communes

**Comment by rehammuzzamil** [comment] 2021-02-18 11:28
@cafootitt I don't have creds to login to the staging server to reproduce the issue at my end. It would be great if you or anyone from the team could share the snapshot of the network tab and the API call with the response. It would help me in further debugging the issue. Thanks!
cc: @p-netm  @githengi

**Comment by cafootitt** [comment] 2021-02-18 13:32
@rehammuzzamil Sent you details on Slack.

**Comment by p-netm** [comment] 2021-02-18 13:44
I think this is sth we needn fix on the frontend. cc @KipSigei https://github.com/joaonuno/tree-model-js#create-a-new-treemodel we can specify the sort order of the children when parsing the hierarchy from the api

**Comment by rehammuzzamil** [comment] 2021-02-18 14:41
> @rehammuzzamil Sent you details on Slack.

Yes, @cafootitt Thanks for sharing. 
I have looked into the API response and it seems that locations are not in alphabetical order. Though I tried to reproduce at my local system with few locations and it worked fine. 
The method which fetches locations from the service layer is marked as @Cacheable which means it caches the results. I am not sure whether a cache is refreshed upon the deployment or not. If it does not, we might need to reload the cache to evict previously saved data. 
@githengi What do you think about this?
Meanwhile, I will try to debug it further.

**Comment by rehammuzzamil** [comment] 2021-02-18 15:17
As discussed with @githengi, to reproduce the scenario at my local we might need to export stage locations DB.

**Comment by rehammuzzamil** [comment] 2021-02-23 07:43
@githengi Identified fix, the issue was in the `opensrp-server-api `repo. Modified data structures from HashSet to **LinkedHashSet** and HashMap to **LInkedHashMap** since LinkedHashMap maintains insertion order of keys, the order in which keys are inserted into LinkedHashMap. Similarly, LinkedHashSet is an ordered and sorted collection of HashSet.

Submitted PR for review @cafootitt.

**Comment by cafootitt** [comment] 2021-02-23 16:25
@rehammuzzamil @githengi I'm still not seeing the locations in alphabetical order after logging in to incognito browser after the Feb 23 server web deployment. What do you see when you log in?

**Comment by rehammuzzamil** [comment] 2021-02-23 19:55
@cafootitt  I just tested again on my local system and it works fine. I believe there may be a caching issue on the staging server. The service layer fetches from the Redis Cache (if it exists) as it is annotated with 
`@Cacheable(value = "locationTreeFromLocation", key = "{ #locationId, #returnTags, #returnStructureCount }")`
 @githengi  @bennsimon  Can you please try flushing out this key through reds-cli on stage server?

**Comment by githengi** [comment] 2021-02-23 20:09
@rehammuzzamil @cafootitt I have flushed the cache. The location hierarchy is now ordered alphabetically

**Closed** 2021-02-24 08:05 UTC
Labels: bug, eusm, fails-qa, has-pr
